name: Dev

on:
  push:
    branches:
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI_COMMIT_MESSAGE: Deployment by CI
  CI_COMMIT_AUTHOR: ci@acmesoftware.com

jobs:
  dev:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Next Tag
        uses: AcmeSoftwareLLC/semver-tag@v1
        id: semver
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          level: patch

      - name: Bump version and push tag
        id: tag_action
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ steps.semver.outputs.next_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: v${{ steps.semver.outputs.prev_tag }}
          toTag: ${{ steps.tag_action.outputs.new_tag }}
          fetchReviewers: true

      - name: Create dev release
        uses: ncipollo/release-action@v1
        id: release
        with:
          tag: ${{ steps.tag_action.outputs.new_tag }}
          name: ${{ steps.tag_action.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: true
