name: PR Version

on:
  pull_request_target:
    types:
      - opened
    branches:
      - main
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pr-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine Increment Level
        id: increment
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "level=minor" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.pull_request.base.ref }}" == "develop" ]]; then
            echo "level=patch" >> $GITHUB_OUTPUT
          else
            echo "level=patch" >> $GITHUB_OUTPUT
          fi

      - name: Generate Next Tag
        uses: AcmeSoftwareLLC/semver-tag@v1
        id: semver
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          level: ${{ steps.increment.outputs.level }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            :rocket: The next version will be **${{ steps.semver.outputs.next_tag }}** ! :rocket:
