name: PR Version

on:
  pull_request_target:
    types:
      - opened
    branches:
      - main
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pr-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Perform semantic version
        uses: paulhatch/semantic-version@v5.4.0
        id: versioning
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-rc${increment}"
          bump_each_commit: false
          search_commit_body: true

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            :rocket: The next version will be **${{ steps.versioning.outputs.version_tag }}** ! :rocket:
