name: PR Validator

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  pr-validator:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: thehanimo/pr-title-checker@v1.4.3
        id: check
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-validator.json

      - name: Add comment to fix PR title
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.check.outputs.success == 'false'}}
        with:
          header: "PR Title Check"
          recreate: true
          message: |
            ### 🚨 PR Title Needs Formatting
            The title of this PR needs to be formatted correctly and include an JIRA Reference. 
            Please update the title to match the format `[JMACS-###] description`. Example:
            * `[JMACS-123] fix typo in README.md`

      - name: Add comment that PR title is fixed
        if: ${{ steps.check.outputs.success == 'true'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "PR Title Check"
          recreate: true
          message: |
            ### ✅ PR Title Formatted Correctly
            The title of this PR has been updated to match the correct format. Thank you!

      - name: Check Labels
        id: check-labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: fix,feature,meta
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true

      - name: Add comment that labels are missing
        if: ${{ steps.check-labels.outputs.label_check == 'failure' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "PR Label Check"
          recreate: true
          message: |
            ### 🚨 Labels are missing
            The PR is missing the required labels. Please add at least one of the following labels:
            * `fix`
            * `feature`

      - name: Validate PR title format
        run: |
          if [ "${{ steps.check.outputs.success }}" = "true" ]; then
            echo "PR title format is correct."
            exit 0
          else
            echo "PR title is not formatted correctly. Please update the title to match the format."
            exit 1
          fi
